First_uni_project/urls.py
from django.contrib import admin
from django.urls import path, include
from project import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.Home, name="home_page"),
    path("project/", include("project.urls", namespace="project")),
    path("logout", views.user_logout, name="logout"), 
]

project/urls.py
from project import views
from django.urls import path

app_name = "project"

urlpatterns=[
    path("register/", views.Register, name="register"),
    path("login/", views.user_login, name="login"),
    path("", views.groupList.as_view(), name="group"),
    path("<int:pk>/group_detail", views.Group_Detail.as_view(), name="group_detail"),
    path("<int:pk>/update", views.Group_Update.as_view(), name="group_update"),
    path("<int:pk>/delete", views.Delete_Group.as_view(), name="group_delete"),
    path("create/", views.Create_Group.as_view(), name="group_creation"), 
    path("<int:pk>/",views.send, name="detail"),
    path("getMessages/<int:pk>/", views.getMessage, name="getMessage"),
    path('request/sent/', views.request_sent, name='request_sent'),
    path('request/pending/', views.request_pending, name='request_pending'),
    path("admin/dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("admin/approve/<int:pk>/", views.approved_request, name="approve_request"),
    path("admin/reject/<int:pk>/", views.rejected_request, name="reject_request"),
    path("send_request/<int:pk>/", views.SendRequest, name="send_request"),
    path("weather/", views.weather, name="weather"),
    path('group/<int:group_pk>/remove_member/<int:user_pk>/', views.remove_member, name='remove_member'),
    # path("username/", views.User_list.as_view(), name="user_list"),
    # path('group/<int:group_pk>/add_member/<int:user_pk>/', views.add, name='add_member'),
    path('group/<int:group_pk>/user_list/', views.User_list.as_view(), name='user_list'),
    path('group/<int:group_pk>/add_member/<int:user_pk>/', views.add, name='add_member'),


    #path("project/<int:pk>/",views.send_message, name="send"),

]

project/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    profile_name = models.CharField(max_length=264,)

    profile_last_name = models.CharField(max_length=264,)

    profile_department = models.CharField(max_length=264,)

    profile_age = models.PositiveIntegerField()

    profile_pic = models.ImageField(upload_to="profile_pictures", blank=True)

    def __str__(self):
        return self.user.username

class GroupChat(models.Model):
    name = models.CharField(max_length=264)
    members = models.ManyToManyField(User)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("project:detail", kwargs={"pk":self.pk})

class Message(models.Model):
    group = models.ForeignKey(GroupChat, on_delete=models.CASCADE, related_name="Group")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.content
    def get_absolute_url(self):
        return reverse("project:detail")

class JoinRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(GroupChat, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=(("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")), default="pending")
    admin_approved = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.user.username} - {self.group.name}"

        

project/views.py
from django.shortcuts import render
from project.form import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse, reverse_lazy
from project.models import GroupChat, Message, JoinRequest, UserProfile
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.contrib.auth.models import User
import requests
import datetime

# Create your views here.
def Home(request):
    return render(request, "project/home_page.html")

    

def fetch_weather_and_forecast(city, api_key, current_wether_url):
    response = requests.get(current_wether_url.format(city, api_key)).json()
    print(response)

    #lat, lon = response["coord"]["lat"], response["coord"]["lon"]
    #forecast_response = requests.get(forecast_url.format(lat, lon, api_key)).json()
    #print("yes", forecast_response)

    weather_data = {
        "city":city,
        "temprature":round(response["main"]["temp"] - 273.15, 2),
        "description": response["weather"][0]["description"],
        "icon": response["weather"][0]["icon"]
    }

    #daily_forecast = []
    #for daily_data in forecast_response["daily"][:5]:
      #  daily_forecast.append({
      #      "day":datetime.datetime.fromtimestamp(daily_data["dt"]).strftime("A"),
      #      "min_temp":round(daily_data["temp"]["min"] - 273.15, 2),
      #      "max_temp": round(daily_data["temp"]["max"] - 273.15, 2),
      #      "description": daily_data["weather"][0]["description"],
       #     "icon": daily_data["weather"][0]["icon"],
       # })

    return weather_data#, daily_forecast
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("home_page"))
def Register(request):
    register = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user # here we are doing one to one field

            if "profile_pic" in request.FILES:
                profile.profile_pic = request.FILES["profile_pic"]

            profile.save()

            register = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, "project/registration.html", context={"register":register, "user_form":user_form, "profile_form":profile_form})

def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(request ,username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse("home_page"))

            else:
                return HttpResponse("ACCOUNT IS NOT ACTIVE")

        else:
            return HttpResponse("ACCOUNT DOES'NT EXIST")

    else:
        return render(request, "project/login.html", {})


    

class groupList(ListView):
    context_object_name = "groups"
    model = GroupChat
    template_name = "project/groups_list.html"


def send(request, pk):
    group = get_object_or_404(GroupChat, pk=pk)
    msg = Message.objects.filter(group=group)

    if request.method == "POST":
        pm = request.POST.get("message")

        #if pm.is_valid():
        content = pm
        author = request.user
        message = Message(author=author, content=content, group=group)
        message.save()
        return HttpResponseRedirect("/project/{}/".format(pk))
            #return HttpResponse("Message sent successfully")

        #else:
            #print(pm.errors)

    return render(request, "project/messages.html", context={"group":group, "messages":msg})
    
def getMessage(request, pk):
    group = get_object_or_404(GroupChat, pk=pk)
    messages = Message.objects.filter(group=group).order_by("timestamp")
    messages_data = [{'author': msg.author.username, 'content': msg.content, 'timestamp': msg.timestamp.strftime('%Y-%m-%d %H:%M:%S')} for msg in messages]
    return JsonResponse({"messages": messages_data})

@staff_member_required
def admin_dashboard(request):
    pending_requests = JoinRequest.objects.filter(status="pending")
    return render(request, 'project/admin_manage_requests.html', {'pending_requests': pending_requests})

@staff_member_required
def approved_request(request, pk):
    join_request = get_object_or_404(JoinRequest, pk=pk)
    join_request.status="approved"
    join_request.admin_approved=True
    join_request.save()
    messages.success(request, 'Join request approved successfully!')

    join_request.group.members.add(join_request.user)

    return redirect("project:admin_dashboard")

@staff_member_required
def rejected_request(request, pk):
    join_request = get_object_or_404(JoinRequest, pk=pk)
    join_request.status = "rejected"
    join_request.save()
    messages.info(request, 'Join request rejected.')
 
    return redirect("project:admin_dashboard")

@login_required
def SendRequest(request, pk):
    group = get_object_or_404(GroupChat, pk=pk)
    user = request.user
    join_request, created = JoinRequest.objects.get_or_create(user=user, group=group)

    if user.is_staff:
        join_request.status = "approved"
        join_request.save()

    if created:
        return render(request, "project/request_sent.html", {"group":group})

    elif join_request.status == "pending":
        return render(request, "project/request_pending.html", {"group":group})

    elif join_request.status == "approved":
        return redirect("project:detail", pk=pk)

    elif join_request.status == "rejected":
        join_request.status = "pending"
        join_request.save()
        return render(request, "project/request_pending.html", {"group":group})

    return HttpResponse("Something went wrong.")


def request_sent(request):
    return render(request, 'request_sent.html')

def request_pending(request):
    return render(request, 'request_pending.html')
    


def weather(request):
    API_KEY = "f33c83b0a846ef9f0f649056c37c5da3"
    current_weather_url = "https://api.openweathermap.org/data/2.5/weather?q={}&appid={}"
    #forecast_url = "https://api.openweathermap.org/data/3.0/onecall?lat={}&lon={}&exclude=hourly,daily&appid={}"
    if request.method == "POST":
        city = request.POST["city"]
        weather_data = fetch_weather_and_forecast(city, API_KEY, current_weather_url)


        context={
            "weather_data":weather_data, 
            #"daily_forecast": daily_forecast,
        }
        return render(request, "project/city_weather.html", context)

    else:
        return render(request, "project/city_weather.html", context=None)

class Group_Detail(DetailView):
    context_object_name = "Group"
    model = GroupChat
    template_name = "project/Group_detail.html"

class Delete_Group(DeleteView):
    contaxt_object_name = "Group"
    model = GroupChat
    success_url = reverse_lazy("project:group")

class Create_Group(CreateView):
    fields = ["name"]
    model = GroupChat
    template_name = "project/Group_creation.html"

    def form_valid(self, form):
        group = form.save(commit=False)
        group.save()
        
        # Add the current user as a member and admin of the group
        group.members.add(self.request.user)
        
        # Automatically approve the group creator as an admin member
        JoinRequest.objects.create(
            user=self.request.user,
            group=group,
            status="approved",
            admin_approved=True
        )

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("project:group")

class Group_Update(UpdateView):
    fields = {"name"}
    model = GroupChat
    template_name="project/Update_group.html"

@staff_member_required
def remove_member(request, group_pk, user_pk):
    group = get_object_or_404(GroupChat, pk=group_pk)
    user = get_object_or_404(User, pk=user_pk)
    
    if user in group.members.all():
        group.members.remove(user)
        join_request = JoinRequest.objects.filter(
            user=user,
            group=group
        ).first()
        if join_request:
            join_request.status = "pending"
            join_request.admin_approved = False
            join_request.save()
            messages.success(request, f'{user.username} has been removed from the group.')
        else:
            messages.warning(request, f'{user.username} is not a member of the group.')

    return redirect(reverse('project:group_detail', kwargs={'pk': group_pk}))



class User_list(ListView):
    context_object_name = "Users"
    model = User
    template_name = "project/user_list.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        group_pk = self.kwargs['group_pk']
        group = GroupChat.objects.get(pk=group_pk)
        context['Group'] = group
        context['group_pk'] = group_pk
        return context

@staff_member_required
def add(request, group_pk, user_pk):
    group = get_object_or_404(GroupChat, pk=group_pk)
    user = get_object_or_404(User, pk=user_pk)

    if not user in group.members.all():
        group.members.add(user)
        join_request = JoinRequest.objects.filter(
            user=user,
            group=group

templates/project/Group_detail.html
{% extends "project/home_page.html" %}
{% block body_block %}
<title>Group Details</title>
<style>
    h2, h3 {
        color: #000000;
        text-align: center;
    }
    ol {
        background: #fff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
        width: 80%;
        list-style: none;
        padding-left: 0;
        margin: 0 auto;
    }
    .list2 {
        padding: 10px;
        border-bottom: 1px solid #f2f2f2;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    li:last-child {
        border-bottom: none;
    }
    .remove {
        background-color: #4caf50;
        color: white;
        padding: 5px 20px;
        text-decoration: none;
        border-radius: 4px;
        transition: background-color 0.3s;
    }
    a:hover {
        background-color: #45a049;
    }
    .user-list-link {
        margin-top: 20px;
        background-color: #007bff;
        padding: 10px 20px;
        border-radius: 5px;
        color: white;
        text-decoration: none;
        transition: background-color 0.3s;
    }
    .user-list-link:hover {
        background-color: #0056b3;
    }
    .list {
        inline-size: 100%;
    }
</style>

<h2>Group Name: {{ Group.name }}</h2>

<h3>Members:</h3>
<ol class="list">
{% for member in Group.members.all %}
    <li class="list2">
        {{ member.username }}
        {% if user.is_staff %}
            {% if not member.is_staff %}
                <a class="remove" href="{% url "project:remove_member" Group.pk member.pk %}">Remove</a>
            {% endif %}
        {% endif %}
    </li>
{% endfor %}
</ol>
{% if user.is_staff %}
    <a class="user-list-link" href="{% url 'project:user_list' group_pk=Group.pk %}">User List</a>
{% endif %}
{% endblock %}

templates/project/admin_manage_requests.html
{% extends "project/home_page.html" %}
{% block body_block %}
<style>
    

    .navbar {
        color: #fff;
        width: 100%;
        padding: 10px 0;
        text-align: center;
    }

    h1 {
        text-align: center;
        margin-bottom: 20px;
        font-size: 3em;
        padding:50px;
        color: #000000;
    }

    table {
        width: 100%;
        margin: auto;
        border-collapse: collapse;
        background: #fff;
        border-radius: 10px;
        overflow: hidden;
        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
    }

    th, td {
        padding: 15px;
        text-align: left;
    }

    th {
        background: #4caf50;
        color: white;
        font-size: 1.1em;
    }

    td {
        border-bottom: 1px solid #f2f2f2;
    }

    tr:hover {
        background: #f1f1f1;
    }

    button {
        border: none;
        color: white;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 14px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 5px;
        transition: background-color 0.3s;
    }

    button.approve {
        background-color: #4caf50;
    }

    button.approve:hover {
        background-color: #45a049;
    }

    button.reject {
        background-color: #f44336;
    }

    button.reject:hover {
        background-color: #d32f2f;
    }

    form {
        display: inline-block;
    }
</style>

<h1>Pending Join Requests</h1>
<table>
    <tr>
        <th>User</th>
        <th>Group</th>
        <th>Status</th>
        <th>Actions</th>
    </tr>
    <tbody>
        {% for request in pending_requests %}
        <tr>
            <td>{{ request.user.username }}</td>
            <td>{{ request.group.name }}</td>
            <td>{{ request.status }}</td>
            <td>
                <form action="{% url 'project:approve_request' request.id %}" method="post">
                    {% csrf_token %}
                    <button class="approve" type="submit">Approve</button>
                </form>
                <form action="{% url 'project:reject_request' request.id %}" method="post">
                    {% csrf_token %}
                    <button class="reject" type="submit">Reject</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/project/groups_list.html
{% extends "project/home_page.html" %}
{% block body_block %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f2f2f2;
        margin: 0;
        padding: 0;
    }

    h1 {
        text-align: center;
        margin-top: 20px;
        color: #333;
    }

    ol {
        list-style-type: none;
        padding: 0;
        margin: 20px;
    }

    li {
        margin-bottom: 10px;
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-bottom: 1px solid #ccc;
        padding-bottom: 10px;
    }

    form {
        display: flex;
        align-items: center;
    }

    button {
        background-color: #007bff;
        color: white;
        border: none;
        padding: 8px 12px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    button:hover {
        background-color: #0056b3;
    }

    .group-name {
        font-size: 1.2em;
    }

    .group-action {
        margin-left: auto;
    }
    .group-creation-link a {
        display: inline-block;
        background-color: #28a745;
        color: white;
        padding: 8px 12px;
        border-radius: 5px;
        text-decoration: none;
        transition: background-color 0.3s ease;
    }

    .group-creation-link a:hover {
        background-color: #218838;
    }
</style>
{% if user.is_staff %}
<div class="group-creation-link">
    <a href="{% url "project:group_creation" %}">Create a New Group</a>
</div>
{% endif %}
<h1>Please choose one of these groups!</h1>

<ol>
    {% for group in groups %}
    <li>
        <span class="group-name">{{ group.name }}</span>
        <form method="POST" action="{% url 'project:send_request' pk=group.id %}">
            {% csrf_token %}
            <input type="hidden" name="group_id" value="{{ group.id }}">
            <button type="submit" class="group-action">Join</button>
        </form>
    </li>
    {% endfor %}
</ol>
{% endblock %}

templates/project/home_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-iKbEMuOkH4FVSz8AwUpnP+5y3E7hChv5leWdrDNr5ssJLi0H8rWIsnYmX2gS8Rv2" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>Group Chats</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-image: url("{% static 'Images/DSC9624.jpg' %}");
            background-size: cover;
            background-position: center;
            background-attachment: fixed;
        }
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
            background-color: #333;
            color: #fff;
            padding: 10px 0;
            font-size: 14px;
            border: none;
            position: relative; /* Add this line */
        }
        .navbar-default .navbar-nav>li>a {
            color: #000000;
        }
        .navbar-default .navbar-nav>li>a:hover {
            color: #ddd;
        }
        .brand-image {
            max-height: 50px; /* Adjust as needed */
            margin-right: 20px; /* Space between images */
        }

        .content-container {
            position: relative;
            z-index: 1;
            max-width: 1200px;
            margin: 20px auto;
            padding: 20px;
            background-color: rgba(255, 255, 255, 0.9);
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
        }
        .welcome-message {
            margin: 20px 0;
            padding: 40px;
            background-color: #ffffff;
            border-radius: 10px;
            text-align: center;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
        }
        .welcome-message h2 {
            margin-top: 0;
            font-size: 2.5em;
            color: #333;
        }
        .welcome-message p {
            font-size: 1.2em;
            color: #555;
        }
        .weather-info {
            text-align: center;
            margin-top: 20px;
            padding: 20px;
            background-color: #e9ecef;
            border-radius: 5px;
        }
        .weather-info h1, .weather-info h2, .weather-info p {
            margin: 10px 0;
            color: #333;
        }
        .auth-links {
            text-align: center;
            margin-top: 250px;
        }
        .auth-links a {
            display: block;
            margin: 10px 0;
        }
    </style>
</head>
<body>
    {%if user.is_authenticated %}
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><img class="brand-image" src="{% static 'Images/project.jpeg' %}" alt=""></li>
            <li><img class="brand-image" src="{% static 'Images/project2.jpeg' %}" alt=""></li>
        </ul>
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'home_page' %}">Home</a></li>
                <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                <li><a class="navbar-link" href="{% url 'project:group' %}">Groups</a></li>
                <li><a class="navbar-link" href="{% url 'project:weather' %}">Weather</a></li>
                {% if user.is_staff %}
                <li><a class="navbar-link" href="{% url 'project:admin_dashboard' %}">Admin Panel</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="content-container">
        <div id="welcome-message" class="welcome-message">
            <h2>Welcome, {{ user.username }}!</h2>
            <p>We are glad to have you here. Start chatting with your groups or check the current weather in your city.</p>
            <p>Feel free to explore the various features and functionalities available to make the most out of your experience.</p>
        </div>
        {% block body_block %}
        {% endblock %}
    </div>
    {% else %}
    <img class="brand-image" src="{% static 'Images/project.jpeg' %}" alt="">
    <img class="brand-image" src="{% static 'Images/project2.jpeg' %}" alt="">
        
    <div class="content-container auth-links">
        <a href="{% url 'project:login' %}" class="btn btn-info">Log In</a>
        <a href="{% url 'project:register' %}" class="btn btn-success">Create An Account</a>
    </div>
    {% endif %}

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            // Check if the user is on the home page and clear the flag if they are
            if (window.location.pathname === "{% url 'home_page' %}") {
                localStorage.removeItem("welcomeMessageSeen");
            }
    
            // Check if the welcome message should be hidden
            if (localStorage.getItem("welcomeMessageSeen") === "true") {
                document.getElementById("welcome-message").style.display = "none";
            }
    
            // Set the flag when the user leaves the page
            window.addEventListener("beforeunload", function() {
                localStorage.setItem("welcomeMessageSeen", "true");
            });
        });
    </script>
    
</body>
</html>

templates/project/messages.html
{%extends "project/home_page.html"%}
{%block body_block%}
<style>
.container {
    background-color: #e9e9e9;
    border-radius: 10px;
    padding: 10px;
    margin-bottom: 10px;
    box-shadow: 0 2px 5px rgba(255, 255, 255, 0.1);
}
.navbar {
        color: #fff;
        width: 100%;
        padding: 10px 0;
        text-align: center;
}

.container.darker {
    background-color: #ffffff;
}

/* Author Name Styling */
.author {
    margin-bottom: 5px;
    color: #333;
}

/* Message Content Styling */
.content {
    font-weight: bold;
    margin-bottom: 10px;
    color: #ffffff;
}

/* Time Stamp Styling */
.timestamp {
    font-size: 0.8em;
    color: #888;
}

/* Scrollbar Styling */
#display {
    max-height: 400px;
    overflow-y: auto; /* Use auto to show scrollbar only when needed */
    padding: 10px;
    scrollbar-width: thin;
    scrollbar-color: #ccc transparent; /* Customize scrollbar color */
}

/* Input Field and Send Button Styling */
#message {
    width: calc(100% - 80px);
    padding: 10px;
    margin-right: 10px;
    border-radius: 5px;
    border: 1px solid #ccc;
}

#sendBtn {
    padding: 10px 20px;
    background-color: #007bff;
    color: #fff;
    border: none;
    border-radius: 5px;
    cursor: pointer;
}

#sendBtn:hover {
    background-color: #0056b3;
}
    .group-info {
        text-align: center;
        margin-bottom: 20px;
        font-size: 3em;
        color: #bd2929;
    }

    .group-links {
        display: flex;
        justify-content: center;
        margin-bottom: 20px;
    }

    .group-links a {
        margin-right: 20px;
        text-decoration: none;
        color: #007bff;
        font-weight: bold;
        transition: color 0.3s ease;
    }

    .group-links a:hover {
        color: #0056b3;
    }
</style>
<body>
    <div class="group-info">
        <p>Group Name: {{ group.name }}</p>
    </div>
    
    <div class="group-links">
        <a href="{% url 'project:group_detail' pk=group.id %}">Group Details</a>
        {% if user.is_staff %}
            <a href="{% url 'project:group_delete' pk=group.id %}">Delete Group</a>
            <a href="{% url 'project:group_update' pk=group.id %}">Update Group</a>
        {% endif %}
    </div>



    <div id="display">
        
    </div>


<form id="sendMessageForm" method="POST">
    {% csrf_token %}
    {{ send.as_p }}
    <input type="text" name="message" id="message" width="100px"/>
    <button type="submit">Send</button>
</form>


<script>
$(document).ready(function(){
    var autoScroll = true; // Flag to control automatic scrolling

    $('#sendMessageForm').submit(function(e){
        e.preventDefault(); // Prevent the default form submission

        $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(), // Serialize form data
            success: function(response){
                // Assuming the server responds with HTML containing the new message
                $('#display').append(response); // Append the new message
                console.log('Message sent successfully!');

                if (autoScroll) {
                    // Scroll to the bottom of the display area
                    $('#display').scrollTop($('#display')[0].scrollHeight);
                }
            },
            error: function(error){
                console.error('Error:', error);
            }
        });

        // Clear the input field after sending the message
        $('#message').val('');

        // Do not focus on the input field to prevent automatic scrolling
        return false;
    });

    // Function to update messages display
    function updateMessages() {
        $.ajax({
            type: 'GET',
            url: "{% url 'project:getMessage' pk=group.id %}",
            success: function(response){
                // Clear the display area
                $("#display").html('');
                
                // Append each message
                for (var key in response.messages){
                    var temp = "<div class='container darker'><b>" + response.messages[key].author + "</b><p>" + response.messages[key].content + "</p><span class='time-left'>" + response.messages[key].timestamp + "</span></div>";
                    $("#display").append(temp); // Append each message
                }

                if (autoScroll) {
                    // Scroll to the bottom of the display area after updating messages
                    $('#display').scrollTop($('#display')[0].scrollHeight);
                }
            },
            error: function(response){
                alert('An error occurred');
            }
        });
    }

    // Call the updateMessages function initially and then at intervals
    updateMessages(); // Call initially
    setInterval(updateMessages, 1000); // Update messages at intervals (adjust interval time as needed)

    // Event listener for scrolling in the display area
    $('#display').scroll(function(){
        var scrollHeight = $('#display')[0].scrollHeight;
        var scrollTop = $('#display').scrollTop();
        var outerHeight = $('#display').outerHeight();

        // Check if the user has scrolled to the bottom
        if (scrollHeight - scrollTop === outerHeight) {
            autoScroll = true; // Enable automatic scrolling if at the bottom
        } else {
            autoScroll = false; // Disable automatic scrolling if not at the bottom
        }
    });
});
</script>

{%endblock%}